name: Deploy Lambdas

on:
  push:
    branches:
      - develop
      - prod
    paths:
      - 'lambdas/lambda_test/**' # This workflow ONLY runs if files in lambda_test change

jobs:
  deploy:
    name: Deploy lambda_test
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v3

      - name: 🔐 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 🚀 Deploy Lambda function
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: ${{ secrets.LAMBDA_FUNCTION_NAME }}-${{ github.ref_name }}
          code-artifacts-dir: lambdas/lambda_test/
          handler: handler.lambda_handler
          runtime: python3.11
